### ISSUE TITLE
The server socket has failed to bind to [::]:50002 (errno: 98 - Address already in use).

### ISSUE THREAD

**Issue by COST-97** [bytedance/GR-MG#11]
Hello:
In the training script file for training multimodal goal-conditioned policy, I tried to specify the port value (such as 50012) in rdzv_endpoint (or master_port), but the port seems to be set randomly and not specified. Sometimes it reports an error:
```
[W socket.cpp:436] [c10d] The server socket has failed to bind to [::]:50002 (errno: 98 - Address already in use).
[W socket.cpp:436] [c10d] The server socket has failed to bind to 0.0.0.0:50002 (errno: 98 - Address already in use).
[E socket.cpp:472] [c10d] The server socket has failed to listen on any local network address.
```

Do you have any suggestions? Looking forward to your reply.

**Comment by LPY1219** [comment]
It appears there may be some port conflicts. This issue often arises from an abnormal program termination. I recommend terminating any lingering processes or threads and trying again.
