### ISSUE TITLE
Evaluation Error

### ISSUE THREAD

**Issue by danzel-crazy** [bytedance/GR-MG#12]
I try run the evaluation of this repository
but some issues popped out in the terminal 

I want to know how to setup all the CKPT path in the eval.sh 
Also, I show my terminal output in the follwing picture 
Thanks for helping me
![螢幕擷取畫面 2024-12-06 143920](https://github.com/user-attachments/assets/6907985e-0709-4843-b3be-74867e429641)

------------------------------------------------------------------------
Below is my eval.sh 
export EPOCHS= (47)
export CKPT_DIR="/tmp2/danzel/GR-MG/checkpoints/policy"
/// export SD_CKPT="/PATH_TO_GOAL_GEN_MODEL_CKPT/epoch=49-step=51450.ckpt"
export SD_CKPT="/tmp2/danzel/GR-MG/checkpoints/goal/goal_gen.ckpt"
export MESA_GL_VERSION_OVERRIDE=3.3
echo $EPOCHS
echo $CKPT_DIR
/// sudo chmod 777 -R ${CKPT_DIR}

export COUNTER=1
/// Use a for loop to iterate through a list
for epoch in "${EPOCHS[@]}"; do
    export COUNTER=$((${COUNTER} + 1))
    export CUDA_VISIBLE_DEVICES=${COUNTER}
    python3 evaluate/eval.py \
        --ckpt_dir ${CKPT_DIR} \
        --epoch ${epoch} \
        --ip2p_ckpt_path ${SD_CKPT} \
        --config_path ${@:1} &
done
wait

**Comment by lipeiyan-bd** [comment]
Hi,

I believe your evaluation script is mostly correct. The main issue seems to stem from the `torch.load(ckpt_path)` line. Please ensure that my released checkpoint is placed in the correct directory and that the checkpoint filename remains unchanged. This is important because the filename is used to match the `epoch `variable.

**Comment by danzel-crazy** [comment]
![image](https://github.com/user-attachments/assets/fabb4484-5fc4-4b47-9b2c-61d68bfc5f2d)

I fixed the filename issue but face the problem above 
In goal_gen/evaluate.py 
line 30 pretrained_model_dir = "/mnt/bn/lpy-lq/stable_diffusion/instruct-pix2pix"
how to get the config.json

**Comment by danzel-crazy** [comment]
I fix the problem haha
Thanks for helping me
Also, I'm working on some experiment on GR-mg 
We try to extend the idea of progress% with LLM or video generate model to generate better token

**Comment by LPY1219** [comment]
I'm thrilled to hear about your interest in my project. Come on!
