### ISSUE TITLE
A question about the choice of action space and proprioceptive state space.

### ISSUE THREAD

**Issue by Stardust-hyx** [bytedance/GR-MG#2]
Thanks for open-sourcing your great work!
I notice that in `calvin_dataset.py`, you relabel the action to the space relative to the end effector frame, as shown below.

```py
                xyz0 = state_buffer[k][0:3]
                rpy0 = state_buffer[k][3:6]
                rotm0 = euler2rotm(rpy0)
                xyz1 = state_buffer[k+1][0:3]
                rpy1 = state_buffer[k+1][3:6]
                rotm1 = euler2rotm(rpy1)
                gripper1 = state_buffer[k+1][-1]
                delta_xyz = rotm0.T @ (xyz1 - xyz0)
                delta_rotm = rotm0.T @ rotm1
                delta_rpy = rotm2euler(delta_rotm)
                temp_action = np.zeros(7)
                temp_action[:3] = delta_xyz * ACTION_POS_SCALE
                temp_action[3:6] = delta_rpy * ACTION_ROT_SCALE
                temp_action[-1] = (gripper1 + 1.0) / 2.0  # (-1, 1) -> (0, 1)
                action_buffer += [temp_action]
                action_valid += [1]
```

Besides, the proprioceptive state is transformed to the space relative to the first end effector frame of the sequence.

I am curious about the reason behind this. Why not directly using the provided delta Cartesian action and proprioceptive state?

**Comment by LPY1219** [comment]
This approach is well-suited for real-world robot deployment. In practical scenarios, data may be gathered from different collection stations, each with its own coordinate system. Using absolute coordinates could lead to confusion for the model due to these differences. However, expressing coordinates in relative terms can effectively prevent this issue.

**Comment by mbreuss** [comment]
My guess is that the idea is probably inspired from the UMI Gripper that proposed that idea: https://umi-gripper.github.io/

In the UMI paper the authors write:

```Delta action represents each action step relative to its immediate previous action, therefore accumulates error. Absolute action requires a global coordinate frame for all actions, which is difficult to define for in-the-wild data collection```

**Comment by Stardust-hyx** [comment]
Seems like an insightful technique. The authors should put related details and experiment results (if any) in the Appendix of the GR-MG paper in favor of completeness. The readers will be grateful for that.
