### ISSUE TITLE
Ego4d dataset

### ISSUE THREAD

**Issue by dingjiansw101** [bytedance/GR-MG#3]
Thanks for sharing the code of this great work. I want to ask where can I find the train800k.json file of Ego4d dataset? Do you use the Ego4d v1 or v2?

**Comment by LPY1219** [comment]
Hi,
Ego4D does not provide a file named "train800k.json." We sampled 800k video clips ourselves from the original Ego4D (V1) dataset. This process is the same as what was done for GR-1.

**Comment by dingjiansw101** [comment]
> Hi,
> 
> Ego4D does not provide a file named "train800k.json." We sampled 800k video clips ourselves from the original Ego4D (V1) dataset. This process is the same as what was done for GR-1.

Could you provide the script to generate the json?

**Comment by LPY1219** [comment]
I apologize. I used the same script as in GR-1, which hasn't open-sourced the data processing script. As a result, I cannot release it without official authorization.
