### ISSUE TITLE
Some issues about running the code

### ISSUE THREAD

**Issue by RanCao2018** [bytedance/GR-MG#7]
Hi, I have two questions

1.  Does the code `cd /opt/tiger/GR_MG` in main.sh is necessary? It looks like a hard code.
2. When I commented out the above-mentioned code and run `bash ./policy/main.sh  ./policy/config/train.json`, it shows "ModuleNotFoundError: No module named 'policy'"

**Comment by LPY1219** [comment]
Thank you for the reminder. I have already fixed the launch scripts.
