### ISSUE TITLE
Evaluate Result Issue

### ISSUE THREAD

**Issue by zijunfdu** [bytedance/GR-MG#9]
Hi, I tried to test the code with the given ckpt, and didn't change any parameters or codes. But the result is very poor, is there any error in my path config? Thank you very much!
![image](https://github.com/user-attachments/assets/04902173-907c-4b72-b1de-da57365eeab4)
![image](https://github.com/user-attachments/assets/9ecaeca1-e3a8-439d-aaf0-8c7cca95a5ad)
![image](https://github.com/user-attachments/assets/2204084b-d40e-42f1-bcc6-acffcac5e2bc)
![image](https://github.com/user-attachments/assets/ab28fcff-40ac-49eb-a293-17889bba3f6a)

**Comment by lipeiyan-bd** [comment]
Hi Zijun,

Thank you for your interest in our work. Based on the information you provided, I identified two potential issues:

In the eval.sh file, the first line (`cd /PATH/TO/GR_MG/`) has not been modified. This should be updated to reflect the directory where you installed GR-MG.

In the `goal_gen/evaluate.py` file, the `pretrained_model_dir` needs to be updated. This parameter points to the pretrained model from Hugging Face, which provides the pretrained VAE weights. I’ve included the relevant link in the README file. Please note that the checkpoint I provided is only for loading the U-Net weights, as this is the sole trainable module in our goal image generation model.

**Comment by zijunfdu** [comment]
Thank you, peiyan.
I still have some problem about the goal_gen.ckpt file.
 I have downloaded the ckpt-file in GR-MG/resources/IP2P/unet, how can i use this ckpt-file and ensure to load it  rather than the original IP2P/unet/diffusion model .
Could you please interpret the process in detail, thanks a lot!
![image](https://github.com/user-attachments/assets/d15deb5f-39ce-4e23-a78f-350c0da9c5c8)

**Comment by LPY1219** [comment]
Do not place the goal_gen.ckpt file in the `pretrained_model_dir`. Instead, store it in a separate folder and specify its path using the `ckpt_path`parameter.

**Comment by zijunfdu** [comment]
In the begining, I evaluated the code with such path config, Ip2p directs to the origin hugging facelink, only the self.unet directs to the goal_gen.ckpt, but the performance in calvin task ABC_D didn't match the paper results like the below pics. Is there any error in the eval test? Thank you very much!
![image](https://github.com/user-attachments/assets/46159c6b-ca47-4b5e-addf-6b34e78994c3)
![image](https://github.com/user-attachments/assets/0d6cbf31-82e6-4a71-a9fe-03dafc243d36)

**Comment by LPY1219** [comment]
I’m sorry, but based on the information you’ve provided, I’m unable to identify the issue in your setup. Since some people have reported successfully reproducing the results, I believe the open-sourced code is correct. I recommend double-checking your code and ensuring that your configuration aligns with the default settings I provided.
